name: "CI/CD Stage 2 Deploy to Int/Sandbox"

on:
  workflow_call:

permissions: {}

jobs:
  deploy-int-app:
    name: "Deploy Pull Request App Environment"
    uses: ./.github/workflows/reusable-deploy.yml
    with:
      environment: "int"
      type_of_deployment: "app"
      use_mock: "True"
    secrets:
      PROXYGEN_CLIENT_ID: ${{ secrets.PROXYGEN_CLIENT_ID }}
      PROXYGEN_KEY_ID: ${{ secrets.PROXYGEN_KEY_ID }}
      PROXYGEN_PRIVATE_KEY: ${{ secrets.PROXYGEN_PRIVATE_KEY }}

  # Add int end-to-end tests

  deploy-sandbox:
    name: "Deploy Pull Request Sandbox Environment"
    uses: ./.github/workflows/reusable-deploy.yml
    with:
      environment: "sandbox"
      type_of_deployment: "sandbox"
    secrets:
      PROXYGEN_CLIENT_ID: ${{ secrets.PROXYGEN_CLIENT_ID }}
      PROXYGEN_KEY_ID: ${{ secrets.PROXYGEN_KEY_ID }}
      PROXYGEN_PRIVATE_KEY: ${{ secrets.PROXYGEN_PRIVATE_KEY }}

  run-postman-collection:
    name: "Run Postman Collection"
    runs-on: ubuntu-latest
    needs: deploy-sandbox
    steps:
      - name: Checkout Repository
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Run Postman Collection
        uses: ./.github/actions/run-postman-collection
        env:
          SANDBOX_BASE_URL: ${{ needs.deploy-sandbox.outputs.environment_url }}

  deploy-uat-spec:
    name: "Deploy Specification to UAT"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Setup Python Dependencies
        uses: ./.github/actions/setup-python-dependencies
      - name: Setup proxygen
        uses: ./.github/actions/setup-proxygen
        with:
          PROXYGEN_CLIENT_ID: ${{ secrets.PROXYGEN_CLIENT_ID }}
          PROXYGEN_KEY_ID: ${{ secrets.PROXYGEN_KEY_ID }}
          PROXYGEN_PRIVATE_KEY: ${{ secrets.PROXYGEN_PRIVATE_KEY }}
      - name: Deploy Specification to UAT
        run: make deploy-spec-uat-ci
        env:
          # Variables are necessary for spec generation, but aren't used in compiled spec
          ENVIRONMENT: "int"
          PROXYGEN_URL_PATH: "im1-pfs-auth"
          CONTAINER_TAG: "latest"
