name: "CI/CD Stage 1 Deploy to Internal QA"

on:
  workflow_call:

permissions: {}

jobs:
  # TODO: Reuse docker container for int deployment, don't rebuild docker container
  deploy-qa-app:
    name: "Deploy Pull Request App Environment"
    uses: ./.github/workflows/reusable-deploy.yml
    with:
      environment: "internal-qa"
      type_of_deployment: "app"
      use_mock: "True"
    secrets:
      PROXYGEN_CLIENT_ID: ${{ secrets.PROXYGEN_CLIENT_ID }}
      PROXYGEN_KEY_ID: ${{ secrets.PROXYGEN_KEY_ID }}
      PROXYGEN_PRIVATE_KEY: ${{ secrets.PROXYGEN_PRIVATE_KEY }}

  # Add int end-to-end tests
  run-end-to-end-tests:
    name: "Run End to End Tests"
    runs-on: ubuntu-latest
    needs: deploy-qa-app
    steps:
      - name: Checkout Repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Setup Python Dependencies
        uses: ./.github/actions/setup-python-dependencies
      - name: Setup proxygen
        uses: ./.github/actions/setup-proxygen
        with:
          PROXYGEN_CLIENT_ID: ${{ secrets.PROXYGEN_CLIENT_ID }}
          PROXYGEN_KEY_ID: ${{ secrets.PROXYGEN_KEY_ID }}
          PROXYGEN_PRIVATE_KEY: ${{ secrets.PROXYGEN_PRIVATE_KEY }}
      - name: Run End to End Tests
        uses: ./.github/actions/run-end-to-end-tests
        env:
          PROXYGEN_URL_PATH: "im1-pfs-auth"
          PROXY_NAME: "im1-pfs-auth"
          APIGEE_PROXY_NAME: "im1-pfs-auth--internal-qa--im1-pfs-auth"
          TEST_APP_KEYCLOAK_CLIENT_ID: ${{ secrets.TEST_APP_KEYCLOAK_CLIENT_ID }}
          TEST_APP_KEYCLOAK_CLIENT_SECRET: ${{ secrets.TEST_APP_KEYCLOAK_CLIENT_SECRET }}
          TEST_APP_API_KEY: ${{ secrets.TEST_APP_API_KEY }}
          TEST_APP_PRIVATE_KEY: ${{ secrets.TEST_APP_PRIVATE_KEY }}

  # TODO: Reuse docker container for sandbox deployment, don't rebuild docker container
  deploy-qa-sandbox:
    name: "Deploy Pull Request Sandbox Environment"
    uses: ./.github/workflows/reusable-deploy.yml
    with:
      environment: "internal-qa-sandbox"
      type_of_deployment: "sandbox"
    secrets:
      PROXYGEN_CLIENT_ID: ${{ secrets.PROXYGEN_CLIENT_ID }}
      PROXYGEN_KEY_ID: ${{ secrets.PROXYGEN_KEY_ID }}
      PROXYGEN_PRIVATE_KEY: ${{ secrets.PROXYGEN_PRIVATE_KEY }}

  run-postman-collection:
    name: "Run Postman Collection"
    runs-on: ubuntu-latest
    needs: deploy-qa-sandbox
    steps:
      - name: Checkout Repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Run Postman Collection
        uses: ./.github/actions/run-postman-collection
        env:
          SANDBOX_BASE_URL: ${{ needs.deploy-qa-sandbox.outputs.environment_url }}
