name: Deploy Environment

concurrency:
  group: deploy-${{ inputs.environment }}-${{ inputs.type_of_deployment }}-${{ inputs.additional_path || 'default' }}

on:
  workflow_call:
    inputs:
      environment:
        description: "The environment to deploy to., e.g. 'internal-dev', 'internal-qa', 'int"
        # Sandbox not supported in this workflow
        required: true
        type: string
      additional_path:
        description: "Additional path to append to the deployment URL, e.g. 'pr-x'"
        required: false
        type: string
      # temporary_deployment: # TODO: Use variable to set if this is a temporary deployment
      #   description: "Whether this is a temporary deployment, e.g. for a pull request, temporary deployment will be cleared after 3 days"
      #   required: true
      #   type: boolean
      type_of_deployment:
        description: "Type of deployment, e.g. 'app', 'sandbox'"
        required: true
        type: string
      use_mock:
        description: "Whether or not the mock for routing requests is on or off"
        type: string
        required: false

    outputs:
      environment_url:
        description: "The URL of the deployed environment"
        value: ${{ jobs.deploy-environment.outputs.environment_url }}
      proxygen_path_url:
        description: "The URL path for the Proxygen API"
        value: ${{ jobs.deploy-environment.outputs.proxygen_path_url }}

    secrets:
      PROXYGEN_CLIENT_ID:
        required: true
        description: "Client ID for Proxygen CLI"
      PROXYGEN_KEY_ID:
        required: true
        description: "Key ID for Proxygen CLI"
      PROXYGEN_PRIVATE_KEY:
        required: true
        description: "Private key for Proxygen CLI"

permissions: {}

env:
  CONTAINER_TAG: ${{inputs.type_of_deployment}}-${{ github.sha }}
  PROXYGEN_DOCKER_REGISTRY_URL: 958002497996.dkr.ecr.eu-west-2.amazonaws.com/im1-pfs-auth
  USE_MOCK: ${{ inputs.use_mock }}

jobs:
  validate-inputs:
    name: "Validate Inputs"
    runs-on: ubuntu-latest
    steps:
      - name: "Check type_of_deployment input"
        run: |
          case "${{ inputs.environment }}" in
            internal-dev|internal-dev-sandbox)
              ;;
            *)
              echo "Invalid environment: ${{ inputs.environment }}. Allowed values are: internal-dev, internal-dev-sandbox."
              exit 1
              ;;
          esac

  build-and-push-container:
    name: "Build & Push Container"
    needs: validate-inputs
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout code"
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Setup Python Dependencies
        uses: ./.github/actions/setup-python-dependencies
      - name: Setup proxygen
        uses: ./.github/actions/setup-proxygen
        with:
          PROXYGEN_CLIENT_ID: ${{ secrets.PROXYGEN_CLIENT_ID }}
          PROXYGEN_KEY_ID: ${{ secrets.PROXYGEN_KEY_ID }}
          PROXYGEN_PRIVATE_KEY: ${{ secrets.PROXYGEN_PRIVATE_KEY }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 # v3.11.1
      - name: "Build ${{inputs.type_of_deployment}} container"
        run: make ${{inputs.type_of_deployment}}-build
      - name: Check Docker Containers
        run: docker images
      - name: "Push ${{inputs.type_of_deployment}} container"
        run: make ${{inputs.type_of_deployment}}-push

  deploy-environment:
    name: "Deploy Environment"
    runs-on: ubuntu-latest
    needs: build-and-push-container
    environment:
      name: ${{ inputs.environment }}
      url: ${{ steps.deploy-environment-url.outputs.environment_url }}
    outputs:
      environment_url: ${{ steps.deploy-environment-url.outputs.environment_url }}
      proxygen_path_url: ${{ steps.proxygen-url-path.outputs.proxygen_url_path }}
    steps:
      - name: "Output PROXYGEN_URL_PATH"
        id: proxygen-url-path
        run: echo "PROXYGEN_URL_PATH=${{ inputs.additional_path && format('im1-pfs-auth-{0}', inputs.additional_path) || 'im1-pfs-auth' }}" >> $GITHUB_ENV
      - name: "Output Environment URL"
        id: deploy-environment-url
        run: echo "ENVIRONMENT_URL=https://${{ inputs.environment }}.api.service.nhs.uk/$PROXYGEN_URL_PATH" >> $GITHUB_OUTPUT
      - name: "Checkout code"
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Setup Python Dependencies
        uses: ./.github/actions/setup-python-dependencies
      - name: Setup proxygen
        uses: ./.github/actions/setup-proxygen
        with:
          PROXYGEN_CLIENT_ID: ${{ secrets.PROXYGEN_CLIENT_ID }}
          PROXYGEN_KEY_ID: ${{ secrets.PROXYGEN_KEY_ID }}
          PROXYGEN_PRIVATE_KEY: ${{ secrets.PROXYGEN_PRIVATE_KEY }}
      - name: Deploy environment
        run: make deploy-ci
        env:
          ENVIRONMENT: ${{ inputs.environment }}
          PROXYGEN_URL_PATH: ${{ env.PROXYGEN_URL_PATH }}
      - name: "Check Deployment"
        run: cat specification/x-nhsd-apim/x-nhsd-apim.generated.yaml
