name: Generate Postman

concurrency:
  group: ${{ format('generate-postman-collection-{0}-{1}', inputs.environment, inputs.additional_path || 'default') }}

on:
  workflow_call:
    inputs:
      environment:
        description: "The environment to deploy to., e.g. 'internal-dev', 'internal-qa', 'int'"
        required: true
        type: string
      additional_path:
        description: "Additional path to append to the deployment URL, e.g. 'pr-x'"
        required: false
        type: string

env:
  POSTMAN_COLLECTION_FILE_NAME: "postman_collection.json"
  POSTMAN_COLLECTION_PATH: "specification/assets/"
  POSTMAN_COLLECTION_BASE_URL: ${{ format('https://{0}.api.service.nhs.uk/im1-pfs-auth{1}', inputs.environment, inputs.additional_path && format('-{0}', inputs.additional_path) || '') }}

jobs:

  generate-postman-collection:
    name: Generate Postman Collection
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout code"
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Generate postman collection
        uses: ./.github/actions/generate-postman-collection

  test-postman:
    name: Test Postman Collection
    needs: generate-postman-collection
    runs-on: ubuntu-latest
    steps:
      - name: Test Postman Collection
        shell: bash
        run: make postman-test
